trainer: VGAETrainer_Joint_PNB
params:
  protein_dim: 283
  gene_dim: 114
  sub_dim: 2048
  z_dim: 128
  sub_node: 4
  optimizer_name: 'Adam'
  lr: 0.00_1
  beta_start_value: 1
  beta_end_value: 1
  beta_n_iterations: 10000
  head_num: 1
  beta_start_iteration: 10000