params:
  beta_end_value: 1
  beta_n_iterations: 80000
  beta_start_iteration: 25000
  beta_start_value: 1
  gamma_end_value: 0.0001
  gamma_start_value: 1
  gene_dim: 2
  graph_loss_weight: 1
  head_num: 1
  lr: 0.001
  optimizer_name: Adam
  scale: 1
  sub_dim: 2048
  sub_node: 25
  z_dim: 128
trainer: soScope_Gaussian
