params:
  beta_end_value: 1
  beta_n_iterations: 10000
  beta_start_iteration: 5000
  beta_start_value: 1
  gamma_end_value: 0.01
  gamma_start_value: 1
  gene_dim: 10
  lr: 0.0001
  optimizer_name: Adam
  scale: 0.5
  sub_dim: 2048
  sub_node: 1
  z_dim: 128
trainer: sc_NB
